//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media()
        {
            this.MediaInsert = new HashSet<MediaInsert>();
        }
    
        public int MediaID { get; set; }
        public Nullable<int> MediaTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MediaPath { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> ArchivedAt { get; set; }
        public Nullable<int> ArchivedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual MediaType MediaType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaInsert> MediaInsert { get; set; }
    }
}
