//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLWebsite.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TLWebsiteDTEEntities1 : DbContext
    {
        public TLWebsiteDTEEntities1()
            : base("name=TLWebsiteDTEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogComment> BlogComments { get; set; }
        public virtual DbSet<BlogPost> BlogPosts { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MediaInsert> MediaInserts { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<PostTag> PostTags { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<StoryComment> StoryComments { get; set; }
        public virtual DbSet<StoryPost> StoryPosts { get; set; }
        public virtual DbSet<TextInsert> TextInserts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
