//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLWebsite.Data
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogComment> BlogComment { get; set; }
        public virtual DbSet<BlogPost> BlogPost { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<MediaInsert> MediaInsert { get; set; }
        public virtual DbSet<MediaType> MediaType { get; set; }
        public virtual DbSet<PostTag> PostTag { get; set; }
        public virtual DbSet<Story> Story { get; set; }
        public virtual DbSet<StoryComment> StoryComment { get; set; }
        public virtual DbSet<StoryPost> StoryPost { get; set; }
        public virtual DbSet<TextInsert> TextInsert { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
